export const GET_ALL_COMMENT = 'GET_ALL_COMMENT';
export const GET_ALL_COMMENT_SAGA = 'GET_ALL_COMMENT_SAGA';

export const INSERT_COMMENT = 'INSERT_COMMENT'
export const INSERT_COMMENT_SAGA = 'INSERT_COMMENT_SAGA'

export const VISIBLE_EDIT_COMMENT = 'VISIBLE_EDIT_COMMENT';
export const EDIT_COMMENT_SAGA = 'EDIT_COMMENT_SAGA';

export const DELETE_COMMENT_SAGA = 'DELETE_COMMENT_SAGA';

export const PUT_ID_VISIBLE = 'PUT_ID_VISIBLE';
