export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA';
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const PUT_PROJECT_DETAIL = 'PUT_PROJECT_DETAIL';
export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';


