export const GET_LIST_PROJECT = 'GET_LIST_PROJECT';
export const GET_LIST_PROJECT_SAGA = 'GET_LIST_PROJECT_SAGA';

export const GET_ALL_PROJECT = 'GET_ALL_PROJECT';
export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA'

export const REMOVE_USER_PROJECT_API = 'REMOVE_USER_PROJECT_API'