export const CREATE_TASK_SAGA = 'CREATE_TASK_SAGA'

export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA';
export const GET_TASK_DETAIL = 'GET_TASK_DETAIL';

export const UPDATA_STATUS_TASK_SAGA = 'UPDATA_STATUS_TASK_SAGA';

export const UPDATA_TASK_SAGA = 'UPDATA_TASK_SAGA';


export const CHANGE_TASK_MODAL = 'CHANGE_TASK_MODAL';

export const CHANGE_ASSIGNESS = 'CHANGE_ASSIGNESS';
export const REMOVE_ASSIGNESS = 'REMOVE_ASSIGNESS';


export const HANDLE_CHANGE_POST_API_SAGA = 'HANDLE_CHANGE_POST_API_SAGA'
