export const GET_USER_SEARCH = 'GET_USER_SEARCH';

export const GET_USER_SAGA = 'GET_USER_SAGA';

export const DELETE_USER_SAGA = 'DELETE_USER_SAGA';

export const EDIT_USER_SAGA = 'EDIT_USER_SAGA';
export const EDIT_USER = 'EDIT_USER';


export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA';
export const GET_USER_BY_PROJECT_ID = 'GET_USER_BY_PROJECT_ID';

export const ADD_USER_PROJECT_API = 'ADD_USER_PROJECT_API';

export const SIGNUP_ERR = 'SIGNUP_ERR'


